apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argocd
  namespace: local-argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/teochenglim/argocd-demo'
    targetRevision: 'main'
    path: 'local-argo'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: local-argo  # Target namespace for deployment
  syncPolicy:
    automated:
      prune: true   # Enables automatic pruning of resources
      selfHeal: true  # Enables automatic healing of discrepancies
